#include "../include/std_lib_facilities_4.h"
#include "../include/Graph.h"
#include "../include/Window.h"
#include "../include/GUI.h"
#include "../include/Simple_window.h"
#include "tile.h"
#include "calculator.h"
